services:
  backend:
    #image: mohdsalimkhatib/gravity-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gravity-backend
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: learningdb
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD}
      PORT: 8080
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - gravity-network
    volumes:
      - ./uploads:/app/uploads

  postgres:
    image: postgres:15-alpine
    container_name: gravity-postgres
    environment:
      POSTGRES_DB: learningdb
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 2
    restart: unless-stopped
    networks:
      - gravity-network

  frontend:
    # Use 'build' to tell compose to look for a Dockerfile in the current directory ('.')
    #image: mohdsalimkhatib/gravity-frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Map port 80 and 443 on your host machine to the container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/ssl:ro
    # Optional: Name the container explicitly for easy reference
    container_name: react_app_container
    # Optional: Automatically restart the container if it stops
    restart: always
    networks:
      - gravity-network

volumes:
  postgres_data:
    driver: local
networks:
  gravity-network:
    driver: bridge
